datafresh/accounts/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^$', 'datafresh.accounts.views.dashboard', 
        name='dashboard'),
    url(r'^entrar/$', 'django.contrib.auth.views.login', 
        {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^sair/$', 'django.contrib.auth.views.logout', 
        {'next_page': 'core:home'}, name='logout'),
    url(r'^cadastre-se/$', 'datafresh.accounts.views.register', 
        name='register'),

    url(r'^nova-senha/$', 'datafresh.accounts.views.password_reset', 
        name='password_reset'),
    url(r'^confirmar-nova-senha/(?P<key>\w+)/$', 
        'datafresh.accounts.views.password_reset_confirm', 
        name='password_reset_confirm'),

    url(r'^editar/$', 'datafresh.accounts.views.edit', 
        name='edit'),    
    url(r'^editar-senha/$', 'datafresh.accounts.views.edit_password', 
        name='edit_password'),
)

datafresh/core/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('datafresh.core.views',
    url(r'^$', 'home', name='home'),
    url(r'^contato/$', 'contact', name='contact'),
)

datafresh/forum/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('datafresh.forum.views',
    url(r'^$', 'index', name='index'),
    url(r'^tag/(?P<tag>[\w_-]+)/$', 'index', name='index_tagged'),
    url(r'^respostas/(?P<pk>\d+)/correta/$', 'reply_correct', 
        name='reply_correct'),
    url(r'^respostas/(?P<pk>\d+)/incorreta/$', 'reply_incorrect', 
        name='reply_incorrect'),
    url(r'^(?P<slug>[\w_-]+)/$', 'thread', name='thread'),
)

datafresh/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('datafresh.core.urls', namespace='core')),
    url(r'^conta/', include('datafresh.accounts.urls', namespace='accounts')),
    url(r'^cursos/', include('datafresh.courses.urls', namespace='courses')),
    url(r'^forum/', include('datafresh.forum.urls', namespace='forum')),    
    url(r'^admin/', include(admin.site.urls)),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

datafresh/core/models.py
from django.db import models

# Create your models here.

datafresh/core/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return render(request, 'home.html')

def contact(request):
    return render(request, 'contact.html')

datafresh/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="vídeos materiais diversos para pessoas com interesse em bi big data data science" />
    <title>Datafresh</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>
<body>
<div class="header">
    <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
        <a class="pure-menu-heading" href="{% url 'core:home' %}">datafresh</a>
        <ul>
            <li class="pure-menu-selected"><a href="{% url 'core:home' %}">INÍCIO</a></li>
            <li><a href="{% url 'courses:index' %}">CURSOS</a></li>
            <li><a href="{% url 'forum:index' %}">FÓRUM</a></li>
            <li><a href="{% url 'core:contact' %}">CONTATO</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:dashboard' %}">PAINEL</a></li>
            <li><a href="{% url 'accounts:logout' %}">SAIR</a></li>
            {% else %}
            <li><a href="{% url 'accounts:login' %}">ENTRAR</a></li>
            {% endif %}
        </ul>
    </div>
</div>
<div class="content">
    {% if messages %}
    <div class="pure-g-r content-ribbon">
        <aside class="pure-u-1">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </aside>
    </div>
    {% endif %}
    {% block content %}{% endblock %}
    <div class="footer">
        datafresh - entregando informação e compartilhando conhecimento.
    </div>
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
{% block scripts %}{% endblock %}
</body>
</html>

datafresh/core/templates/contact.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h1>Envie a sua mensagem:</h1>
        <p>Você pode falar com a gente, sempre que precisar. Tanto por e-mail ou pelas redes sociais. Abaixo estão os nossos contatos.</p>
        <h4>Fale conosco</h4>
        <ul>
            <li>E-mail: <a href="mailto:contato@datafresh.org">datafresh@datafresh.com.br</a></li>
            <li>Twitter: <a href="https://twitter.com/datafresh"></a></li>
            <li>Facebook: <a href="https://twitter.com/datafresh"></a></li>
        </ul>
    </div>
</div>
{% endblock %}

datafresh/core/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    Bem-vindo a nossa área de Compartilhamento da Informação e Conhecimento-(CIC).
                </h1>
                <h2 class="splash-subhead">
                    O nosso objetivo é contribuir com a comunidade de big data e analytics, simplificando o aprendizado a distância, oferecendo treinamentos e conteúdos de qualidade, para aqueles que querem trocar informação e conhecimento.
                </h2>
                <p>
                    <a href="#" class="pure-button primary-button">Saiba mais</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Vídeo-aulas e diversos materiais</h4>
            <h3>Conheça os nossos Cursos</h3>
            <p>
                A nossa plataforma é muito simples e prática. Qualquer pessoa interessada em obter informação e conhecimento, consegue facilmente acessar as várias vídeo-aulas ou outros materiais digitais, como por exemplo: pdf, slides, imagens, etc...
            </p>
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Vídeo-aulas e diversos materiais">
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Fórum de dúvidas">
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Fórum de dúvidas</h4>
            <h3>Tenha acesso a um ambiente dinâmico e interativo</h3>
            <p>
                Aqui você terá acesso a um sistema de fórum. Possibilitando que você e outros participantes, possam interagir entre si. Isto torna o processo de aprendizado mais dinâmico e rico.
                Favorecendo principalmente, na troca de conhecimento, em um aumento na comunicação entre os participantes e no compartilhamento de informações.
            </p>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Atividades</h4>
            <h3>Aprenda praticando</h3>
            <p>
                Aqui você vai aprender na prática, através de atividades desafiadoras. Isso serve para fortalecer o seu aprendizado durante o Curso e também apontar as suas dificuldades no assunto. 
                Todo o controle de notas e resolução das atividades é controlado pela plataforma, facilitando sua vida
                e também de todos os envolvidos.
            </p>
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Atividades">
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Mural de Avisos">
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Mural de Avisos</h4>
            <h3>Fique por dentro de tudo o que está acontecendo</h3>
            <p>
                Nunca foi tão fácil e simples, organizar e comunicar avisos ou notícias, sobre a aula, a atividade do
                dia, ou mesmo sobre eventos importantes de interesse comum a todos. 
                Fique por dentro de tudo o que está acontecendo e não perca nenhuma oportunidade de aprender cada vez mais.
            </p>
        </div>
    </div>
</div>
{% endblock %}